const adindivuduel = [
    {
      id: 1,
      title: 'Malaga',
      adDescription: 'Cozy Retreat with Private Bathroom & Kitchen - Enjoy a tranquil stay in our charming home, complete with a private bathroom and fully-equipped kitchen. Only a 10-minute walk from the metro station and nearby supermarkets, you will have easy access to the city best attractions while having a peaceful haven to return to.',
      imageSrc: 'imgicons/01-outside.jpg',
      image2Src: 'imgicons/01-living-room.jpg',
      image3Src: 'imgicons/01-bedroom.jpg',
      image4Src: 'imgicons/01-kitchen.jpg',
      wifiIconSrc:'imgicons/A-10-wi-fi.png', 
      wifiIconAlt:'icon-wifi-figurel',
      parkingIconSrc: 'imgicons/A-06-parking.png', 
      parkingIconAlt: 'icon-parking',
     
      price:'54 /night',
    },
      {
        id: 2,
        title: 'Albacete',
        adDescription:'Welcome to our urban oasis featuring modern amenities and a serene ambiance. Your private en-suite bathroom and kitchenette make for a comfortable stay. Conveniently located just 10 minutes away from the bustling metro station and well-stocked supermarkets.',
        imageSrc: 'imgicons/02-outside.jpg',
        image2Src: 'imgicons/02-kitchen.jpg',
        image3Src: 'imgicons/02-bedroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png',
        parkingIconAlt: 'icon-parking',
        price:'60 /night',
      },
      {
        id: 3,
        title: 'Madrid',
        adDescription:'Make yourself at home in our lovely space, boasting a private bathroom and well-equipped kitchen. With the metro station and supermarkets just a short 10-minute walk away, you will find exploring the city a breeze while having a cozy retreat to unwind.',
        imageSrc: 'imgicons/03-outside.jpg',
        image2Src: 'imgicons/03-bedroom.jpg',
        image3Src: 'imgicons/03-washroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png', 
        parkingIconAlt: 'icon-parking',
        price:'30 /night',
      },
      {
        id: 4,
        title: 'Lisbon',
        adDescription:'Discover serenity in our peaceful abode, complete with a private bathroom and fully-stocked kitchen. Only a quick 10-minute stroll to the metro station and supermarkets, you will experience the perfect blend of convenience and relaxation.',
        imageSrc: 'imgicons/04-outside.jpg',
        image2Src: 'imgicons/04-bedroom.jpg',
        image3Src: 'imgicons/04-kitchen.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png',
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png', 
        parkingIconAlt: 'icon-parking',
        price:'25 /night',
      },
    
      {
        id: 5,
        title: 'Cuenca',
        adDescription:'Discover serenity in our peaceful abode, complete with a private bathroom and fully-stocked kitchen. Only a quick 10-minute stroll to the metro station and supermarkets, you will experience the perfect blend of convenience and relaxation.',
        imageSrc: 'imgicons/05-outside.jpg',
        image2Src: 'imgicons/05-bedroom.jpg',
        image3Src: 'imgicons/05-washroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png', 
        parkingIconAlt: 'icon-parking',
        price:'20 /night',
      },
      {
        id: 6,
        title: 'Barcelona',
        adDescription:' Indulge in a charming stay with your own private bathroom and kitchen facilities. Just a 10-minute walk from the metro station and nearby supermarkets, our home offers a convenient and delightful experience.',
        imageSrc: 'imgicons/06-outside.jpg',
        image2Src: 'imgicons/06-kitchen.jpg',
       image3Src: 'imgicons/01-bedroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png',
        parkingIconAlt: 'icon-parking',
        price:'30 /night',
      },
       {
        id: 7,
        title: 'Salamanca',
        adDescription:' Indulge in a charming stay with your own private bathroom and kitchen facilities. Just a 10-minute walk from the metro station and nearby supermarkets, our home offers a convenient and delightful experience.',
        imageSrc: 'imgicons/07-front.jpg',
        image2Src: 'imgicons/06-kitchen.jpg',
        image3Src: 'imgicons/06-bedroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png',
        parkingIconAlt: 'icon-parking',
        price:'30 /night',
      },
      {
        id: 8,
        title: 'Murcia',
        adDescription:' Indulge in a charming stay with your own private bathroom and kitchen facilities. Just a 10-minute walk from the metro station and nearby supermarkets, our home offers a convenient and delightful experience.',
        imageSrc: 'imgicons/08-front.jpg',
        image2Src: 'imgicons/06-kitchen.jpg',
        image3Src: 'imgicons/01-bedroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png',
        parkingIconAlt: 'icon-parking',
        price:'30 /night',
      },
      {
        id: 9,
        title: 'Navaluenga',
        adDescription:' Indulge in a charming stay with your own private bathroom and kitchen facilities. Just a 10-minute walk from the metro station and nearby supermarkets, our home offers a convenient and delightful experience.',
        imageSrc: 'imgicons/09-front.jpg',
        image2Src: 'imgicons/06-kitchen.jpg',
        image3Src: 'imgicons/01-bedroom.jpg',
        image4Src: 'imgicons/02-washroom.jpg',
        wifiIconSrc:'imgicons/A-10-wi-fi.png', 
        wifiIconAlt:'icon-wifi-figurel',
        parkingIconSrc: 'imgicons/A-06-parking.png',
        parkingIconAlt: 'icon-parking',
        price:'30 /night',
      },
    
    ];
  
    export default adindivuduel;