const ad = [
  {
    id: 1,
    title: 'Malaga',
    description: 'Cozy Retreat with Private Bathroom & Kitchen ',
    imageSrc: 'imgicons/01-outside.jpg', 
    wifiIconSrc:'imgicons/A-10-wi-fi.png', 
    wifiIconAlt:'icon-wifi-figurel',
    parkingIconSrc: 'imgicons/A-06-parking.png', 
    parkingIconAlt: 'icon-parking',
    price:'54 /night',
  },
    {
      id: 2,
      title: 'Albacete',
      description: 'Urban Oasis with Modern Amenities ',
      imageSrc: 'imgicons/02-outside.jpg',
      wifiIconSrc:'imgicons/A-10-wi-fi.png', 
      wifiIconAlt:'icon-wifi-figurel',
      parkingIconSrc: 'imgicons/A-06-parking.png',
      parkingIconAlt: 'icon-parking',
      price:'60 /night',
    },
    {
      id: 3,
      title: 'Madrid',
      description: 'House Near Metro & Supermarket',
      imageSrc: 'imgicons/03-outside.jpg',
      wifiIconSrc:'imgicons/A-10-wi-fi.png', 
      wifiIconAlt:'icon-wifi-figurel',
      parkingIconSrc: 'imgicons/A-06-parking.png', 
      parkingIconAlt: 'icon-parking',
      price:'30 /night',
    },
    {
      id: 4,
      title: 'Lisbon',
      description: 'Tranquil Haven Near Metro & Supermarket ',
      imageSrc: 'imgicons/04-outside.jpg',
      wifiIconSrc:'imgicons/A-10-wi-fi.png',
      wifiIconAlt:'icon-wifi-figurel',
      parkingIconSrc: 'imgicons/A-06-parking.png', 
      parkingIconAlt: 'icon-parking',
      price:'25 /night',
    },
  
    {
      id: 5,
      title: 'Cuenca',
      description: 'Charming Accommodation with Private Amenities',
      imageSrc: 'imgicons/05-outside.jpg',
      wifiIconSrc:'imgicons/A-10-wi-fi.png', 
      wifiIconAlt:'icon-wifi-figurel',
      parkingIconSrc: 'imgicons/A-06-parking.png', 
      parkingIconAlt: 'icon-parking',
      price:'20 /night',
    },
    {
      id: 6,
      title: 'Barcelona',
      description: 'Accommodation Close to Metro & Supermarket',
      imageSrc: 'imgicons/06-outside.jpg',
      wifiIconSrc:'imgicons/A-10-wi-fi.png', 
      wifiIconAlt:'icon-wifi-figurel',
      parkingIconSrc: 'imgicons/A-06-parking.png',
      parkingIconAlt: 'icon-parking',
      price:'30 /night',
    },
  
  ];

  export default ad;