const ad = [
  {
    id: 1,
    title: 'Malaga',
    description: 'Description', 
    wifiIconSrc:'icons8-wi-fi-48.png', 
    wifiIconAlt:'icon-wifi-figurel',
    smokingIconSrc:'icons8-smoking-40.png', 
    smokingIconAlt:'icon-smoker',
    imageSrc: '01-outside.jpg',
    price:'200',
  },
    {
      id: 2,
      title: 'Albacete',
      description: 'Discover a hidden gem in this cozy getaway, offering modern amenities and a warm ambiance that will make you feel right at home during your stay.',
      imageSrc: '02-outside.jpg',
      wifiIconSrc:'icons8-wi-fi-48.png', 
      wifiIconAlt:'icon-wifi-figurel',
      smokingIconSrc:'icons8-smoking-40.png', 
      smokingIconAlt:'icon-smoker',
      alt:'icon-smoker',
      price:'200',
    },
    {
      id: 3,
      title: 'Madrid',
      description: 'Description',
      imageSrc: '03-outside.jpg',
      wifiIconSrc:'icons8-wi-fi-48.png', 
      wifiIconAlt:'icon-wifi-figurel',
      smokingIconSrc:'icons8-smoking-40.png', 
      smokingIconAlt:'icon-smoker',
      alt:'icon-smoker',
      price:'200',
    },
    {
      id: 4,
      title: 'Lisbon',
      description: 'Description',
      imageSrc: '04-outside.jpg',
      wifiIconSrc:'icons8-wi-fi-48.png', 
      wifiIconAlt:'icon-wifi-figurel',
      smokingIconSrc:'icons8-smoking-40.png', 
      smokingIconAlt:'icon-smoker',
      alt:'icon-smoker',
      price:'200',
    },
  
    {
      id: 5,
      title: 'Cuenca',
      description: 'Description',
      imageSrc: '05-outside.jpg',
      wifiIconSrc:'icons8-wi-fi-48.png', 
      wifiIconAlt:'icon-wifi-figurel',
      smokingIconSrc:'icons8-smoking-40.png', 
      smokingIconAlt:'icon-smoker',
      alt:'icon-smoker',
      price:'200',
    },
    {
      id: 6,
      title: 'Barcelona',
      description: 'Description',
      imageSrc: '06-outside.jpg',
      wifiIconSrc:'icons8-wi-fi-48.png', 
      wifiIconAlt:'icon-wifi-figurel',
      smokingIconSrc:'icons8-smoking-40.png', 
      smokingIconAlt:'icon-smoker',
      alt:'icon-smoker',
      price:'200',
    },
  
  ];

  export default ad;